### ISSUE TITLE
Cant run this program on anaconda 3

### ISSUE THREAD

**Issue by CHANANEHassen** [sciforce/lyon#1]
Hi. 
I'm new to python env. i've tried to run this code on windows via notebook.
However Im gerring this error : cannot import name 'LyonCalc'

**Comment by akademi4eg** [comment]
Hey!
This has been tested only on linux. If you have cygwin or something similar installed on your windows machine, you can try building manually https://github.com/sciforce/lyon#manual (it'd probably produce a dll instead of so-file).

But overall I'd suggest to find a linux environment as it would be much more straightforward to use this tool.
